# Generated by Django 4.2.7 on 2026-03-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_add_recruiter_approval_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number in international format (e.g., +1234567890)', max_length=20, null=True),
        ),
    ]
