# Generated by Django 4.2.7 on 2026-03-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_otp_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
