import { jsPDF } from 'jspdf'
import { formatINR } from './format'

/**
 * Builds a simple text-based salary breakup report. Reuses jsPDF (already
 * a dependency for resume export) — this draws text directly rather than
 * rasterizing a DOM element, since a data table doesn't need pixel-perfect
 * visual fidelity the way a resume template does.
 */
export function exportSalaryBreakdownPdf(breakdown, filename = 'salary-breakdown.pdf') {
  const pdf = new jsPDF('p', 'mm', 'a4')
  const marginX = 20
  let y = 25

  pdf.setFont('helvetica', 'bold')
  pdf.setFontSize(18)
  pdf.text('Salary Breakdown', marginX, y)
  y += 6
  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(10)
  pdf.setTextColor(120)
  pdf.text(`${breakdown.regime === 'new' ? 'New' : 'Old'} Tax Regime · Generated by MyTechZ Salary Calculator`, marginX, y)
  pdf.setTextColor(0)
  y += 12

  function row(label, monthly, annual, { bold = false } = {}) {
    pdf.setFont('helvetica', bold ? 'bold' : 'normal')
    pdf.setFontSize(11)
    pdf.text(label, marginX, y)
    pdf.text(formatINR(monthly), 120, y, { align: 'right' })
    pdf.text(`${formatINR(annual)}/yr`, 190, y, { align: 'right' })
    y += 7
  }

  function sectionTitle(text) {
    pdf.setFont('helvetica', 'bold')
    pdf.setFontSize(9)
    pdf.setTextColor(100)
    pdf.text(text.toUpperCase(), marginX, y)
    pdf.setTextColor(0)
    y += 6
  }

  sectionTitle('Earnings')
  row('Basic Salary', breakdown.components.basic.monthly, breakdown.components.basic.annual)
  row('HRA', breakdown.components.hra.monthly, breakdown.components.hra.annual)
  row('Special Allowance', breakdown.components.specialAllowance.monthly, breakdown.components.specialAllowance.annual)
  row('Gross Salary', breakdown.gross.monthly, breakdown.gross.annual, { bold: true })
  y += 3

  sectionTitle('Deductions')
  row('Employee PF', breakdown.deductions.employeePf.monthly, breakdown.deductions.employeePf.annual)
  if (breakdown.deductions.employeeEsi.eligible) {
    row('Employee ESI', breakdown.deductions.employeeEsi.monthly, breakdown.deductions.employeeEsi.annual)
  }
  row('Professional Tax', breakdown.deductions.professionalTax.monthly, breakdown.deductions.professionalTax.annual)
  row('Income Tax (TDS)', breakdown.deductions.incomeTax.monthly, breakdown.deductions.incomeTax.annual)
  y += 3

  pdf.setDrawColor(0)
  pdf.line(marginX, y, 190, y)
  y += 8
  row('In-Hand Salary', breakdown.inHand.monthly, breakdown.inHand.annual, { bold: true })

  y += 12
  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(8)
  pdf.setTextColor(150)
  pdf.text('This is an estimate based on standard PF/ESI/tax rules and may differ from your actual payslip.', marginX, y)
  pdf.text('mytechz.com/ai-tools/salary-calculator', marginX, y + 5)

  pdf.save(filename)
}
