# Generated by Django 4.2.7 on 2026-03-15 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('speaker', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], default='online', max_length=20)),
                ('platform', models.CharField(help_text='Platform/Venue name', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('category', models.CharField(choices=[('technology', 'Technology'), ('business', 'Business'), ('career', 'Career Development'), ('education', 'Education'), ('other', 'Other')], default='technology', max_length=50)),
                ('description', models.TextField()),
                ('agenda', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_webinars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'webinars',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=200)),
                ('courses', models.TextField(help_text='Courses offered')),
                ('eligibility', models.TextField(help_text='Eligibility criteria')),
                ('deadline', models.DateField(help_text='Application deadline')),
                ('fees', models.CharField(help_text='Fee structure', max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_admissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admission_posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
